name: 樱花动漫更新自动推送
on:
  schedule:
    - cron: '33 03 * * *'  # 北京时间11:33
    - cron: '30 07 * * *'  # 北京时间15:30
    - cron: '33 11 * * *'  # 北京时间19:33
    - cron: '50 12 * * *'  # 北京时间20:50
  workflow_dispatch:

concurrency:
  group: anime-${{ github.ref }}
  cancel-in-progress: true

jobs:
  anime-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install requests beautifulsoup4

      - name: 执行推送
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: python YHDM动漫更新推送.py

      - name: 提交历史记录
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --local user.name "AutoUpdater"
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git remote set-url origin "https://$REPO_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          
          # 同步最新代码
          git pull origin main --rebase --autostash
          
          git add update_history.json
          if ! git diff --staged --quiet; then
            git commit -m "自动更新: $(date +'%Y-%m-%d %H:%M')"
            git push origin HEAD:main || exit 1
          fi
