name: Scheduled YouTube Video Update Check

on:
  schedule:
    - cron: '5 11 * * *'  # 每天上午 11 点 5 分
    - cron: '33 15 * * *' # 每天下午 15 点 33 分
    - cron: '35 19 * * *' # 每天晚上 7 点 35 分

jobs:
  check-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python script
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          python Youtube动漫更新推送.py
