# .github/workflows/anime-notify.yml
name: 动漫更新自动推送
on:
  schedule:
    - cron: '33 03 * * *'  # 北京时间11:33
    - cron: '30 07 * * *'  # 北京时间15:30
    - cron: '33 11 * * *'  # 北京时间19:33
    - cron: '50 12 * * *'  # 北京时间20:50
  workflow_dispatch:

jobs:
  anime-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          pip install requests beautifulsoup4

      - name: 执行推送
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: python 动漫更新自动微信推送-YHDM.py

      - name: 提交历史记录
        run: |
          git config --global user.name "AutoUpdater"
          git config --global user.email "actions@github.com"
          git add update_history.json
          git diff --staged --quiet || (git commit -m "自动更新: $(date +'%Y-%m-%d %H:%M')" && git push)
