name: 数据库连接测试定时运行

on:
  schedule:
    - cron: '33 03 * * *'  # 北京时间11:33
    - cron: '30 07 * * *'  # 北京时间15:30
    - cron: '33 11 * * *'  # 北京时间19:33
    - cron: '50 12 * * *'  # 北京时间20:50
  workflow_dispatch:

concurrency:
  group: database-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-db-connection:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run Python script
        run: python 数据库连接测试.py
