name: 金山动漫更新自动推送
on:
  schedule:
    - cron: '0,30 1,13 * * *'  # 对应北京时间9:00、9:30、21:00、21:30
    - cron: '0,30 2-12 * * *'  # 对应北京时间10:00-22:30（每半小时一次）
    - cron: '*/15 10-11 * * *' # 对应北京时间18:00-19:30（每15分钟一次）
    # 新增：对应北京时间 11:00 - 11:45（每15分钟一次），12:00 整包含在内
    - cron: '*/15 3-4 * * *'   # UTC 时间 03:00-04:00，对应北京时间 11:00-12:00
  workflow_dispatch:

concurrency:
  group: anime-${{ github.ref }}
  cancel-in-progress: true

jobs:
  anime-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install requests beautifulsoup4

      - name: 执行推送
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: python 金山文档动漫更新.py

      - name: 提交历史记录
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --local user.name "AutoUpdater"
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git remote set-url origin "https://$REPO_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          
          # 同步最新代码
          git pull origin main --rebase --autostash
          
          git add update_history_jinshan.json
          if ! git diff --staged --quiet; then
            git commit -m "自动更新: $(date +'%Y-%m-%d %H:%M')"
            git push origin HEAD:main || exit 1
          fi
